DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE EMPRESA;

USE EMPRESA;

CREATE TABLE ONG(
    IdONG INT NOT NULL,
    TelefonoONG INT(9) NOT NULL,
    DirONG VARCHAR NOT NULL,
    IDEMPRESA_ONG INT NOT NULL
);

ALTER TABLE ONG ADD CONSTRAINT pk_ong PRIMARY KEY(IdONG);
ALTER TABLE ONG ADD CONSTRAINT fk_ong FOREIGN KEY(IDEMPRESA_ONG) REFERENCES EMPRESA(IDEMPRESA);

CREATE TABLE EMPRESA(
    IDEMPRESA INT NOT NULL,
    NOMBRE_EMP TEXT NOT NULL,
    DirEMP VARCHAR NOT NULL,
    TelefonoEMP INT(9)
);

ALTER TABLE EMPRESA ADD CONSTRAINT pk_empresa PRIMARY KEY(IDEMPRESA);

