DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE EMPRESA;

USE EMPRESA;

CREATE TABLE ONG(
    ID_ONG INT NOT NULL,
    NOMBRE_ONG VARCHAR(30) NOT NULL,
    TLF_ONG INT(9) NOT NULL,
    DIR_ONG VARCHAR(50) NOT NULL,
    ID_EMPRESA INT NOT NULL
);

CREATE TABLE EMPRESA(
    ID_EMPRESA INT NOT NULL,
    NOMBRE_EMPRE TEXT NOT NULL,
    DIR_EMPR VARCHAR(50) NOT NULL,
    TLF_EMPR INT(9) NOT NULL
);

CREATE TABLE DEPARTAMENTO(
    ID_DEP INT NOT NULL,
    NOMBRE_DEP TEXT NOT NULL,
    NUM_DEP INT NOT NULL,
    NUM_TRAB INT NOT NULL,
    ID_EMPRESA INT NOT NULL
);

CREATE TABLE EMPLEADOS(
    ID_EMPLEADOS INT NOT NULL,
    NOMBRE_EMPL TEXT NOT NULL,
    TLF_EMPL INT(9) NOT NULL,
    SALARIO INT(4) NOT NULL,
    DIR_EMPL VARCHAR(50) NOT NULL,
    SEXO TEXT NOT NULL,
    APELLIDO1 TEXT NOT NULL,
    APELLIDO2 TEXT NOT NULL,
    FECHA_NAC_EMPL DATE NOT NULL,
    ID_DEP INT NOT NULL
);

CREATE TABLE REPARA(
    FECHA_HORA DATETIME NOT NULL,
    ID_EMPLEADOS INT NOT NULL,
    ID_DISP INT NOT NULL
);

CREATE TABLE DISPOSITIVOS(
    ID_DISP INT NOT NULL,
    DESCRIPCION_DISP VARCHAR(50) NOT NULL,
    MARCA_DISP TEXT NOT NULL
);

CREATE TABLE ORDENADOR(
    ID_ORDENADOR INT NOT NULL,
    DESCRIPCION_ORD VARCHAR(50) NOT NULL,
    MARCA_ORD TEXT NOT NULL,
    TIPO_ORD TEXT NOT NULL,
    ID_DISP INT NOT NULL
);

CREATE TABLE MOVIL(
    ID_MOVIL INT NOT NULL,
    DESCRIPCION_MOV VARCHAR(50) NOT NULL,
    MARCA_MOV TEXT NOT NULL,
    TIPO_MOV TEXT NOT NULL,
    ID_DISP INT NOT NULL
);

CREATE TABLE ACCESORIOS(
    ID_ACCESORIOS INT NOT NULL,
    DESCRIPCION_ACC VARCHAR(50) NOT NULL,
    MARCA_ACC TEXT NOT NULL,
    TIPO_ACC TEXT NOT NULL,
    ID_DISP INT NOT NULL
);

ALTER TABLE ONG ADD CONSTRAINT pk_ong PRIMARY KEY(ID_ONG);

ALTER TABLE EMPRESA ADD CONSTRAINT pk_empresa PRIMARY KEY(ID_EMPRESA);

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT pk_departamento PRIMARY KEY(ID_DEP);

ALTER TABLE EMPLEADOS ADD CONSTRAINT pk_empleados PRIMARY KEY(ID_EMPLEADOS);

ALTER TABLE REPARA ADD CONSTRAINT pk_repara PRIMARY KEY(ID_EMPLEADOS, ID_DISP);

ALTER TABLE DISPOSITIVOS ADD CONSTRAINT pk_dispositivos PRIMARY KEY(ID_DISP);

ALTER TABLE ORDENADOR ADD CONSTRAINT pk_ordenador PRIMARY KEY(ID_ORDENADOR);

ALTER TABLE MOVIL ADD CONSTRAINT pk_movil PRIMARY KEY(ID_MOVIL);

ALTER TABLE ACCESORIOS ADD CONSTRAINT pk_accesorios PRIMARY KEY(ID_ACCESORIOS);


ALTER TABLE ONG ADD CONSTRAINT fk_ong FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA);

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT fk_departamento FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA);

ALTER TABLE EMPLEADOS ADD CONSTRAINT fk_empleados FOREIGN KEY(ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP);

ALTER TABLE REPARA ADD CONSTRAINT fk_repara_empleados FOREIGN KEY(ID_EMPLEADOS) REFERENCES EMPLEADOS(ID_EMPLEADOS);
ALTER TABLE REPARA ADD CONSTRAINT fk_repara_disp FOREIGN KEY(ID_DISP) REFERENCES DISPOSITIVOS(ID_DISP);

ALTER TABLE ORDENADOR ADD CONSTRAINT fk_ordenador FOREIGN KEY(ID_DISP) REFERENCES DISPOSITIVOS(ID_DISP);

ALTER TABLE MOVIL ADD CONSTRAINT fk_movil FOREIGN KEY(ID_DISP) REFERENCES DISPOSITIVOS(ID_DISP);

ALTER TABLE ACCESORIOS ADD CONSTRAINT fk_accesorios FOREIGN KEY(ID_DISP) REFERENCES DISPOSITIVOS(ID_DISP);

INSERT INTO EMPRESA VALUES(589, "E.A / S.A.L", "48220,Poligono Astola, Vizcaya", 669546745);
INSERT INTO ONG VALUES(13783, "SED", 681105991, "Calle Xaudaró 25 Madrid, España", 589);
INSERT INTO DEPARTAMENTO VALUES(34, "Departamento Recursos Humanos", 4, 140, 589);
INSERT INTO DEPARTAMENTO VALUES(65, "Departamento Marketing", 3, 123, 589);
INSERT INTO DEPARTAMENTO VALUES(78, "Departamento Logistica", 7, 99, 589);
INSERT INTO DEPARTAMENTO VALUES(51, "Oficina Numero 1", 2, 75, 589);
INSERT INTO DEPARTAMENTO VALUES(83, "Oficina Numero 2", 1, 65, 589);
INSERT INTO DEPARTAMENTO VALUES(17, "Oficina Numero 3", 5, 23, 589);
INSERT INTO DEPARTAMENTO VALUES(47, "Departamento Informatica", 6, 15, 589);
INSERT INTO EMPLEADOS VALUES(234, "Adrian", 602744712, 2100, "Ruela Antonio, 6, Bajo 8ºF,Los Sotelo del Mirador, España", "");
INSERT INTO EMPLEADOS VALUES(321, "Marta", 627488532, 2300, "Camino Navarrete, 06, 6º D, Paredes Baja, España", "");
INSERT INTO EMPLEADOS VALUES(356, "Damian", 642812232, 1900, "Plaza Centeno, 87, 79º E, San Moreno, España", "");
INSERT INTO EMPLEADOS VALUES(289, "Hector", 681826290, 2100, "Plaza Álvaro, 10, 7º B, Hernando de las Torres, España", "");
INSERT INTO EMPLEADOS VALUES(443, "David", 682140110, 1500, "Camino Acevedo, 98, 11º E, Los Pineda, España", "");
INSERT INTO EMPLEADOS VALUES(192, "Faisan", 675618233, 2200, "Calle Fronton, 34, 3ºD, Amurrio, España", "");
INSERT INTO EMPLEADOS VALUES(538, "Carla", 638782332, 1600, "Andra Mari Kalea 11, 2ºA, Durango,España", "");